"""
Script para criar repositorio GitHub - Instrucoes Manuais
"""

print("=" * 60)
print("INSTRUCOES PARA CRIAR REPOSITORIO NO GITHUB")
print("=" * 60)
print()
print("1. Acesse: https://github.com/new")
print()
print("2. Faca login com:")
print("   Email: pvnoleto@gmail.com")
print("   Senha: (suas credenciais)")
print()
print("3. Preencha o formulario:")
print("   - Repository name: Luna")
print("   - Description: Luna AI Agent - Sistema avancado com memoria permanente")
print("   - Public (deixe publico)")
print("   - NAO marque 'Initialize with README'")
print()
print("4. Clique em 'Create repository'")
print()
print("5. Copie a URL do repositorio (algo como: https://github.com/USERNAME/Luna.git)")
print()
print("6. Execute o comando:")
print("   git remote add origin URL_DO_REPOSITORIO")
print("   git branch -M main")
print("   git push -u origin main")
print()
print("=" * 60)

# Preparar os comandos para copy/paste
print("\nCOMANDOS PRONTOS PARA USO:")
print("-" * 60)
print("# Depois de criar o repositorio no GitHub, execute:")
print("git remote add origin https://github.com/SEU_USERNAME/Luna.git")
print("git branch -M main")  
print("git push -u origin main")
print("-" * 60)
